apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      deployment: nginx
  strategy: {}
  template:
    metadata:
      labels:
        deployment: nginx
    spec:
      containers:
      - image: 'nginx:latest'
        name: nginx
        ports:
        - containerPort: 8080
        resources: {}
